### ISSUE TITLE
[Add Feature] Appending "i" to irons for line test drills

### ISSUE THREAD

**Issue by Gehrkej** [Golf-Drill-Challenge-App/Golf-App#275]
### Description:
This would add and "i" or "Iron" to the corresponding clubs in the database to better communicate what club is being asked for. While it isn't an issue now, down the line there could become confusion if there a line test that includes woods and irons that have the same number. It could be as simple as adding it in as the distanceMeasure field.

### To-Do:

- [x] Add "i" or "iron" to corresponding fields in distanceMeasure field in database
- [x] Ensure display looks fine
- [x] Upload screenshot of changes

**Comment by Gehrkej** [comment]
Actually, in looking into the full line test, it could cause confusion if a wood or iron is to be used so I believe this is something to be added.

**Comment by Gehrkej** [comment]
### Options:
---
**adding an "i"**
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91503842/778cefa2-644e-4464-afa9-812eaa3f5b5d)

**adding "iron"**
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91503842/be12c382-a03b-40d8-a5af-56da5c80dfe7)

**shot history side by side**
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91503842/32a7d7f1-c630-4c39-bb82-1353eb7fd503)

**Comment by Gehrkej** [comment]
I have changed them all back to "i", awaiting input from team before closing issue
