### ISSUE TITLE
Foreign requests: Add "None" for blank screens

### ISSUE THREAD

**Issue by Gehrkej** [Golf-Drill-Challenge-App/Golf-App#333]
## Description:
On the Foreign request screens, they are very blank if there is no content for anything on the tab which might lead to some confusion for the user if it is working or not. Adding in there are no invites currently or nobody on the waitlist or nobody on the blacklist could help with providing feedback to the user.

## Todo:
- [x] Add None text to "Invites"
- [x] Add None text to "Waitlist"
- [x] Add None text to "Blacklist"

## Screenshots: 
![image](https://github.com/user-attachments/assets/a563fd5a-a6c2-4b2c-bf28-1a4f741f05ba)
![image](https://github.com/user-attachments/assets/1dda2ee1-1aae-442a-93ce-a2bfa9b24004)
![image](https://github.com/user-attachments/assets/47e07306-782d-4d5a-9d5e-de94aee301f8)
