### ISSUE TITLE
Users Should be able to delete their account

### ISSUE THREAD

**Issue by Gehrkej** [Golf-Drill-Challenge-App/Golf-App#341]
### Description
Currently the user has no way to delete their account themselves. This might cause some issues when trying to get the app published to the App store. 

### To-do
- [x] Create UI  "Delete Account" button on profile settings modal
- [x] Create UI  "Delete Account" button on Join team screen
- [ ] Create dialog warning users before they take this action
- [ ] Utilize existing delete account functionality found in ban user flow to this flow
