### ISSUE TITLE
Create a function to check if the best_attempt table needs to be updated upon attempt submission

### ISSUE THREAD

**Issue by Gehrkej** [Golf-Drill-Challenge-App/Golf-App#95]
### Issue Description:
Currently upon an attempt being submitted the best_attempt table in the database is not being checked and updated if needed. 

### To-do:
- [x] Fetch best_attempts collection for a drill
- [x] Isolate the best attemepts for a given user
~- [ ] Iterate through all aggOutputs and compare if the new attempt is better (use "lowerIsBetter field" to determine this)~
- [x] Update the given field if the new attempt is better

### Updated To-dos (4-26-2024)
- [x] More testing on empty leaderboard (no attempts on the board). For testing, delete current entries from an existing leaderboard (in "best_attempts" table of Firebase console)
- [x] Do a bit of manual testing for race case (2 different devices / accounts, try to submit drill at same time)
- [x] Remove unused code to avoid future confusion (updateLeaderboard hook, setManualAttempt stuff in leaderboard.js, etc)

### Other Notes:
- Utilize both the `updateLeaderboard` and `useLeaderboard` hooks/functions to accomplish this. They are in the `/hooks` directory

**Comment by Gehrkej** [comment]
Note: comments on #94 have been made where this function will go. A new feature branch will be made for this issue though

**Comment by Gehrkej** [comment]
I have this functional for how the "best_attempts" table is currently structured with only having one criterion as well as having each drill being a map/object. See PR #161 for more information.

**Comment by Gehrkej** [comment]
this issue has merged with #150
